### ISSUE TITLE
Allow indicatorsToFetchByFile to be empty

### ISSUE THREAD

**Issue by vincent-fuchs** [societe-generale/github-crawler#2]
If I want to run the crawler for something else than indicatorsToFetchByFile, I would leave it empty in config.

But this doesn't seem to work :

Caused by: java.lang.UnsupportedOperationException: Empty collection can't be reduced.
at com.societegenerale.githubcrawler.RepositoryEnricher.fetchIndicatorsValues(RepositoryEnricher.kt:163) ~[classes/:na]
at com.societegenerale.githubcrawler.GitHubCrawler$fetchAndParseRepoContent$11.apply(GitHubCrawler.kt:128) ~[classes/:na]
at com.societegenerale.githubcrawler.GitHubCrawler$fetchAndParseRepoContent$11.apply(GitHubCrawler.kt:24) ~[classes/:na]
at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[na:1.8.0_25]
at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[na:1.8.0_25]
at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[na:1.8.0_25]
at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[na:1.8.0_25]
at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[na:1.8.0_25]
at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[na:1.8.0_25]
at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[na:1.8.0_25]
at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[na:1.8.0_25]
at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[na:1.8.0_25]
at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[na:1.8.0_25]
at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1540) ~[na:1.8.0_25]
at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512) ~[na:1.8.0_25]
at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502) ~[na:1.8.0_25]
at java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:747) ~[na:1.8.0_25]
at java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:721) ~[na:1.8.0_25]
at java.util.stream.AbstractTask.compute(AbstractTask.java:316) ~[na:1.8.0_25]
at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731) ~[na:1.8.0_25]
at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[na:1.8.0_25]
at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:902) ~[na:1.8.0_25]
at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1689) ~[na:1.8.0_25]
at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1644) ~[na:1.8.0_25]
at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[na:1.8.0_25]

**Comment by vincent-fuchs** [comment]
duplicated with https://github.com/societe-generale/github-crawler/issues/14
