### ISSUE TITLE
shouldn't crash when fetching commits

### ISSUE THREAD

**Issue by vincent-fuchs** [societe-generale/github-crawler#41]
## Summary

If there's a problem while retrieving commits, it shouldn't crash

## Type of Issue

It is a : 
 - [X] bug
 - [ ] request
 - [ ] question regarding the documentation

## Motivation

job should complete

## Current Behavior

getting below error : 

~~~
Caused by: com.societegenerale.githubcrawler.remote.GitHubResponseDecoder$NoFileFoundFeignException: problem while fetching content, of unknown type
        at com.societegenerale.githubcrawler.remote.GitHubResponseDecoder.decode(RemoteGitHubImpl.kt:405) ~[github-crawler-core-1.0.9.jar!/:1.0.9]
        at feign.SynchronousMethodHandler.decode(SynchronousMethodHandler.java:165) ~[feign-core-9.5.1.jar!/:na]
        at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:136) ~[feign-core-9.5.1.jar!/:na]
        at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:76) ~[feign-core-9.5.1.jar!/:na]
        at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:103) ~[feign-core-9.5.1.jar!/:na]
        at com.societegenerale.githubcrawler.remote.$Proxy57.fetchCommits(Unknown Source) ~[na:1.0.9]
        at com.societegenerale.githubcrawler.remote.RemoteGitHubImpl.fetchCommits(RemoteGitHubImpl.kt:272) ~[github-crawler-core-1.0.9.jar!/:1.0.9]
        at com.societegenerale.githubcrawler.ownership.OwnershipParserImpl.computeOwnershipFor(OwnershipParserImpl.kt:41) ~[github-crawler-core-1.0.9.jar!/:1.0.9]

~~~

## Expected Behavior

job should continue

## Your Environment

* Version used: 1.0.9
* OS and version:
* Version of libs used:

**Comment by vincent-fuchs** [comment]
still valid ?
